# Generated by Django 4.0 on 2021-12-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
