# Generated by Django 4.0 on 2021-12-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='part_model',
            field=models.IntegerField(default=1),
        ),
    ]
